Add support for shell aliases
andrewchambers/janetsh pull request #156
Opened 2019-05-29 13:12 UTC by X4lldux

Adds support for shell aliases with new builtins `alias` & `unalias`. 
```
$ alias ll ls -Alhp
0
$ alias
alias ll ls -Alhp
0
$ alias nope
error: alias: nope not found
1
$ unalias -a
0
```

2019-05-29 20:25 UTC, andrewchambers commented
Reviewing and testing locally now, wont be too long.

2019-05-29 20:41 UTC, X4lldux commented
@andrewchambers don't merge just yet, I have some reservations about not being sh compatible. Your on Gitter?

2019-05-29 20:42 UTC, andrewchambers commented
Yeah, on gitter.

2019-05-29 21:29 UTC, andrewchambers requested changes

2019-05-29 21:29 UTC, andrewchambers commented on src/sh.janet
> +(defn- make-alias-builtin
This code is really nice, but I wonder if it can be simplified by just making alias/unalias regular janet functions. They are slightly uglier to call, but aliases seem to be setup once in an rc file then left alone. Being regular janet functions matches job control.

2019-05-29 21:29 UTC, andrewchambers commented on src/sh.janet
> +  (when-let [bi (*aliases* (first args))]
I would rename this bi, it was originally short for builtin.

2019-05-29 21:29 UTC, andrewchambers commented on test/cases/0016-aliases
> +
A test case executing a mutiple word alias command with multiple args would be nice to have.

2019-06-03 10:23 UTC, andrewchambers commented
I have fixed up this PR, added alias and unalias macro/functions and merged.

2019-06-03 10:23 UTC, closed without merging